import { FolderItemsType } from "@/types/window";
/**
 * [folder, doc content 관련 데이터]
 */

// folder, doc contentKey에 대응하는 아이콘 small버전.
// window창 header 또는 start popup list 아이콘으로 사용됨.
export const contentKeyIcon: Record<string, string> = {
  // folder
  projects: "w95-opened-file-empty-small",
  noname: "w95-opened-file-empty-small",
  computer: "w95-computer-small",
  cDrive: "w95-cDrive-small",
  dDrive: "w95-dDrive-small",
  music: "w95-cd-small",
  recycleBin: "w95-bin-empty-small",
  aboutMe: "w95-me-small",
  calendar: "w95-calendar-small ",
  photos: "w95-camera-small",
  2022: "w95-opened-file-empty-small",
  2023: "w95-opened-file-empty-small",
  2024: "w95-opened-file-empty-small",
  paint: "w95-paint-small",
  // doc
  resume: "w95-resume-small",
  portfolio: "w95-portfolio-small",
  myWebSite: "w95-resume-small",
  internet: "w95-internet-small",
  photo: "w95-photo-small",
  // welcome
  welcome: "w95-tip-small",
  // systemInfo
  systemInfo: "w95-info-small",
};

const defaultFolderData = {
  width: "550px",
  height: "300px",
  iconNm: "",
  contentKey: "",
  iconImgNm: "",
  textColor: "white",
  windowType: "",
  folderItems: [] as FolderItemsType[],
};

export const contentInfo: Record<string, FolderItemsType> = {
  projects: {
    ...defaultFolderData,
    iconNm: "Projects",
    contentKey: "projects",
    iconImgNm: "w95-closed-file",
    textColor: "white",
    windowType: "folder",
    folderItems: [
      {
        ...defaultFolderData,
        iconNm: "MyWebSite",
        contentKey: "myWebSite",
        iconImgNm: "w95-resume",
        textColor: "black",
        windowType: "doc",
      },
    ],
  },
  computer: {
    ...defaultFolderData,
    iconNm: "Computer",
    contentKey: "computer",
    iconImgNm: "w95-computer",
    textColor: "white",
    windowType: "folder",
    folderItems: [
      {
        iconNm: "(C:)",
        contentKey: "cDrive",
        iconImgNm: "w95-cDrive",
        textColor: "black",
        windowType: "childFolder",
        width: "550px",
        height: "300px",
        folderItems: [],
      },
      {
        iconNm: "(D:)",
        contentKey: "dDrive",
        iconImgNm: "w95-dDrive",
        textColor: "black",
        windowType: "childFolder",
        width: "550px",
        height: "300px",
        folderItems: [],
      },
    ],
  },
  music: {
    ...defaultFolderData,
    iconNm: "Music",
    contentKey: "music",
    iconImgNm: "w95-cd",
    textColor: "white",
    windowType: "folder",
    folderItems: [],
  },
  recycleBin: {
    ...defaultFolderData,
    iconNm: "Recycle Bin",
    contentKey: "recycleBin",
    iconImgNm: "w95-bin-empty",
    textColor: "white",
    windowType: "folder",
    folderItems: [],
  },
  aboutMe: {
    ...defaultFolderData,
    iconNm: "About Me",
    contentKey: "aboutMe",
    iconImgNm: "w95-me",
    textColor: "white",
    windowType: "folder",
    folderItems: [
      {
        ...defaultFolderData,
        iconNm: "Resume",
        contentKey: "resume",
        iconImgNm: "w95-resume",
        textColor: "black",
        windowType: "doc",
      },
      {
        ...defaultFolderData,
        iconNm: "Miasoft PowerPoint - Portfolio",
        contentKey: "portfolio",
        iconImgNm: "w95-portfolio",
        textColor: "black",
        windowType: "doc",
      },
      {
        ...defaultFolderData,
        iconNm: "Noname",
        contentKey: "noname",
        iconImgNm: "w95-closed-file",
        textColor: "black",
        windowType: "childFolder",
        folderItems: [],
      },
    ],
  },
  photos: {
    ...defaultFolderData,
    iconNm: "Photos",
    contentKey: "photos",
    iconImgNm: "w95-camera",
    textColor: "white",
    windowType: "folder",
    folderItems: [
      {
        ...defaultFolderData,
        iconNm: "2022",
        contentKey: "2022",
        iconImgNm: "w95-closed-file",
        textColor: "black",
        windowType: "childFolder",
        folderItems: [
          {
            ...defaultFolderData,
            iconNm: "1",
            contentKey: "photo",
            iconImgNm: "w95-photo",
            textColor: "black",
            windowType: "doc",
          },
        ],
      },
      {
        iconNm: "2023",
        contentKey: "2023",
        iconImgNm: "w95-closed-file",
        textColor: "black",
        windowType: "childFolder",
        width: "550px",
        height: "300px",
        folderItems: [
          {
            ...defaultFolderData,
            iconNm: "1",
            contentKey: "photo",
            iconImgNm: "w95-photo",
            textColor: "black",
            windowType: "doc",
          },
          {
            ...defaultFolderData,
            iconNm: "2",
            contentKey: "photo",
            iconImgNm: "w95-photo",
            textColor: "black",
            windowType: "doc",
          },
          {
            ...defaultFolderData,
            iconNm: "3",
            contentKey: "photo",
            iconImgNm: "w95-photo",
            textColor: "black",
            windowType: "doc",
          },
        ],
      },
      {
        iconNm: "2024",
        contentKey: "2024",
        iconImgNm: "w95-closed-file",
        textColor: "black",
        windowType: "childFolder",
        width: "550px",
        height: "300px",
        folderItems: [],
      },
    ],
  },
  calendar: {
    ...defaultFolderData,
    iconNm: "Calendar",
    contentKey: "calendar",
    iconImgNm: "w95-calendar",
    textColor: "white",
    windowType: "folder",
    folderItems: [],
  },
  paint: {
    ...defaultFolderData,
    iconNm: "Paint",
    contentKey: "paint",
    iconImgNm: "w95-paint",
    textColor: "white",
    windowType: "folder",
    folderItems: [],
  },
  systemInfo: {
    ...defaultFolderData,
    iconNm: "System Info",
    contentKey: "systemInfo",
    iconImgNm: "w95-info",
    textColor: "white",
    windowType: "info",
    folderItems: [],
  },
};
