import { FolderItemsType, InfoType, WindowType } from "@/types/window";

/**
 * [폴더 content 데이터]
 */

// folder타입 윈도우의 child요소중 childFolder Type인 폴더의 child요소
// const folderItems = {
//   // 상위폴더는 aboutMe
//   noname: [],
//   // 상위폴더는 photos
//   2022: [
//     {
//       iconNm: "1",
//       contentKey: "1",
//       iconImgNm: "w95-photo",
//       textColor: "black",
//       windowType: "doc" as WindowType,
//       parentFolderKey: "2022",
//       folderItems: [],
//     },
//   ],
//   2023: [
//     {
//       iconNm: "1",
//       contentKey: "1",
//       iconImgNm: "w95-photo",
//       textColor: "black",
//       windowType: "doc" as WindowType,
//       parentFolderKey: "2023",
//       folderItems: [],
//     },
//     {
//       iconNm: "2",
//       contentKey: "2",
//       iconImgNm: "w95-photo",
//       textColor: "black",
//       windowType: "doc" as WindowType,
//       parentFolderKey: "2023",
//       folderItems: [],
//     },
//     {
//       iconNm: "3",
//       contentKey: "3",
//       iconImgNm: "w95-photo",
//       textColor: "black",
//       windowType: "doc" as WindowType,
//       parentFolderKey: "2023",
//       folderItems: [],
//     },
//   ],
//   2024: [],
// };

// // 윈도우내용 데이터
// export const contentInfo: Record<string, InfoType> = {
//   projects: {
//     ...defaultFolderData,
//     iconNm: "Projects",
//     contentKey: "projects",
//     iconImgNm: "w95-closed-file",
//     textColor: "white",
//     windowType: "folder",
//     left: "20%",
//     top: "30%",
//     folderItems: [
//       {
//         iconNm: "MyWebSite",
//         contentKey: "myWebSite",
//         iconImgNm: "w95-resume",
//         textColor: "black",
//         windowType: "doc" as WindowType,
//         // parentFolderKey: "projects",
//         folderItems: [],
//       },
//     ],
//     // parentFolderKey: "",
//   },
//   computer: {
//     ...defaultFolderData,
//     iconNm: "Computer",
//     contentKey: "computer",
//     iconImgNm: "w95-computer",
//     textColor: "white",
//     windowType: "folder",
//     left: "10%",
//     top: "40%",
//     folderItems: [],
//     // parentFolderKey: "",
//   },
//   music: {
//     ...defaultFolderData,
//     iconNm: "Music",
//     contentKey: "music",
//     iconImgNm: "w95-cd",
//     textColor: "white",
//     windowType: "folder",
//     left: "10%",
//     top: "40%",
//     folderItems: [],
//     // parentFolderKey: "",
//   },
//   recycleBin: {
//     ...defaultFolderData,
//     iconNm: "Recycle Bin",
//     contentKey: "recycleBin",
//     iconImgNm: "w95-bin-empty",
//     textColor: "white",
//     windowType: "folder",
//     left: "10%",
//     top: "40%",
//     folderItems: [],
//     // parentFolderKey: "",
//   },
//   aboutMe: {
//     ...defaultFolderData,
//     iconNm: "About Me",
//     contentKey: "aboutMe",
//     iconImgNm: "w95-me",
//     textColor: "white",
//     windowType: "folder",
//     left: "50%",
//     top: "50%",
//     folderItems: [
//       {
//         iconNm: "Resume",
//         contentKey: "resume",
//         iconImgNm: "w95-resume",
//         textColor: "black",
//         windowType: "doc" as WindowType,
//         folderItems: [],
//         // parentFolderKey: "aboutMe",
//       },
//       {
//         iconNm: "Miasoft PowerPoint - Portfolio",
//         contentKey: "portfolio",
//         iconImgNm: "w95-ppt",
//         textColor: "black",
//         windowType: "doc" as WindowType,
//         folderItems: [],
//         // parentFolderKey: "aboutMe",
//       },
//       {
//         iconNm: "Noname",
//         contentKey: "noname",
//         iconImgNm: "w95-closed-file",
//         textColor: "black",
//         windowType: "childFolder" as WindowType,
//         folderItems: folderItems["noname"],
//         // parentFolderKey: "aboutMe",
//       },
//     ],
//     // parentFolderKey: "",
//   },
//   photos: {
//     ...defaultFolderData,
//     iconNm: "Photos",
//     contentKey: "photos",
//     iconImgNm: "w95-camera",
//     textColor: "white",
//     windowType: "folder",
//     left: "20%",
//     top: "8%",
//     folderItems: [
//       {
//         iconNm: "2022",
//         contentKey: "2022",
//         iconImgNm: "w95-closed-file",
//         textColor: "black",
//         windowType: "childFolder",
//         folderItems: folderItems["2022"],
//         // parentFolderKey: "photos",
//       },
//       {
//         iconNm: "2023",
//         contentKey: "2023",
//         iconImgNm: "w95-closed-file",
//         textColor: "black",
//         windowType: "childFolder",
//         folderItems: folderItems["2023"],
//         // parentFolderKey: "photos",
//       },
//       {
//         iconNm: "2024",
//         contentKey: "2024",
//         iconImgNm: "w95-closed-file",
//         textColor: "black",
//         windowType: "childFolder",
//         folderItems: folderItems["2024"],
//         // parentFolderKey: "photos",
//       },
//     ],
//     // parentFolderKey: "",
//   },
//   // internet: {
//   //   ...defaultFolderData,
//   //   iconNm: "Internet",
//   //   contentKey: "internet",
//   //   iconImgNm: "w95-internet",
//   //   textColor: "white",
//   //   windowType: "doc",
//   //   left: "40%",
//   //   top: "10%",
//   //   folderItems: [],
//   // },
//   calendar: {
//     ...defaultFolderData,
//     iconNm: "Calendar",
//     contentKey: "calendar",
//     iconImgNm: "w95-calendar",
//     textColor: "white",
//     windowType: "folder",
//     left: "40%",
//     top: "10%",
//     folderItems: [],
//     // parentFolderKey: "",
//   },
//   paint: {
//     ...defaultFolderData,
//     iconNm: "Paint",
//     contentKey: "paint",
//     iconImgNm: "w95-paint",
//     textColor: "white",
//     windowType: "folder",
//     left: "20%",
//     top: "10%",
//     folderItems: [],
//     // parentFolderKey: "",
//   },
// };

const defaultFolderData = {
  width: "550px",
  height: "300px",
  left: "20%",
  top: "30%",
  iconNm: "",
  contentKey: "",
  iconImgNm: "",
  textColor: "white",
  windowType: "",
  folderItems: [] as FolderItemsType[],
};

export const contentInfo: Record<string, InfoType> = {
  projects: {
    ...defaultFolderData,
    left: "20%",
    top: "30%",
    iconNm: "Projects",
    contentKey: "projects",
    iconImgNm: "w95-closed-file",
    textColor: "white",
    windowType: "folder",
    folderItems: [
      {
        ...defaultFolderData,
        iconNm: "MyWebSite",
        contentKey: "myWebSite",
        iconImgNm: "w95-resume",
        textColor: "black",
        windowType: "doc",
      },
    ],
  },
  computer: {
    ...defaultFolderData,
    left: "10%",
    top: "40%",
    iconNm: "Computer",
    contentKey: "computer",
    iconImgNm: "w95-computer",
    textColor: "white",
    windowType: "folder",
    folderItems: [],
  },
  music: {
    ...defaultFolderData,
    left: "10%",
    top: "40%",
    iconNm: "Music",
    contentKey: "music",
    iconImgNm: "w95-cd",
    textColor: "white",
    windowType: "folder",
    folderItems: [],
  },
  recycleBin: {
    ...defaultFolderData,
    left: "10%",
    top: "40%",
    iconNm: "Recycle Bin",
    contentKey: "recycleBin",
    iconImgNm: "w95-bin-empty",
    textColor: "white",
    windowType: "folder",
    folderItems: [],
  },
  aboutMe: {
    ...defaultFolderData,
    left: "50%",
    top: "50%",
    iconNm: "About Me",
    contentKey: "aboutMe",
    iconImgNm: "w95-me",
    textColor: "white",
    windowType: "folder",
    folderItems: [
      {
        ...defaultFolderData,
        iconNm: "Resume",
        contentKey: "resume",
        iconImgNm: "w95-resume",
        textColor: "black",
        windowType: "doc",
      },
      {
        ...defaultFolderData,
        iconNm: "Miasoft PowerPoint - Portfolio",
        contentKey: "portfolio",
        iconImgNm: "w95-ppt",
        textColor: "black",
        windowType: "doc",
      },
      {
        ...defaultFolderData,
        iconNm: "Noname",
        contentKey: "noname",
        iconImgNm: "w95-closed-file",
        textColor: "black",
        windowType: "childFolder",
        folderItems: [],
      },
    ],
  },
  photos: {
    ...defaultFolderData,
    left: "20%",
    top: "8%",
    iconNm: "Photos",
    contentKey: "photos",
    iconImgNm: "w95-camera",
    textColor: "white",
    windowType: "folder",
    folderItems: [
      {
        ...defaultFolderData,
        iconNm: "2022",
        contentKey: "2022",
        iconImgNm: "w95-closed-file",
        textColor: "black",
        windowType: "childFolder",
        folderItems: [
          {
            ...defaultFolderData,
            iconNm: "1",
            contentKey: "1",
            iconImgNm: "w95-photo",
            textColor: "black",
            windowType: "doc",
          },
        ],
      },
      {
        iconNm: "2023",
        contentKey: "2023",
        iconImgNm: "w95-closed-file",
        textColor: "black",
        windowType: "childFolder",
        width: "550px",
        height: "300px",
        left: "20%",
        top: "30%",
        folderItems: [
          {
            ...defaultFolderData,
            iconNm: "1",
            contentKey: "1",
            iconImgNm: "w95-photo",
            textColor: "black",
            windowType: "doc",
          },
          {
            ...defaultFolderData,
            iconNm: "2",
            contentKey: "2",
            iconImgNm: "w95-photo",
            textColor: "black",
            windowType: "doc",
          },
          {
            ...defaultFolderData,
            iconNm: "3",
            contentKey: "3",
            iconImgNm: "w95-photo",
            textColor: "black",
            windowType: "doc",
          },
        ],
      },
      {
        iconNm: "2024",
        contentKey: "2024",
        iconImgNm: "w95-closed-file",
        textColor: "black",
        windowType: "childFolder",
        width: "550px",
        height: "300px",
        left: "20%",
        top: "30%",
        folderItems: [],
      },
    ],
  },
  calendar: {
    ...defaultFolderData,
    left: "10%",
    top: "40%",
    iconNm: "Calendar",
    contentKey: "calendar",
    iconImgNm: "w95-calendar",
    textColor: "white",
    windowType: "folder",
    folderItems: [],
  },
  paint: {
    ...defaultFolderData,
    left: "10%",
    top: "40%",
    iconNm: "Paint",
    contentKey: "paint",
    iconImgNm: "w95-paint",
    textColor: "white",
    windowType: "folder",
    folderItems: [],
  },
};
